/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiActionRouteImport } from './routes/api/action'

const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRoute = ApiActionRouteImport.update({
  id: '/api/action',
  path: '/api/action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/mentions': typeof MentionsRoute
  '/api/action': typeof ApiActionRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/query': typeof ApiQueryRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/mentions': typeof MentionsRoute
  '/api/action': typeof ApiActionRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/query': typeof ApiQueryRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/mentions': typeof MentionsRoute
  '/api/action': typeof ApiActionRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/query': typeof ApiQueryRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dms'
    | '/inbox'
    | '/mentions'
    | '/api/action'
    | '/api/inbox'
    | '/api/query'
    | '/api/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dms'
    | '/inbox'
    | '/mentions'
    | '/api/action'
    | '/api/inbox'
    | '/api/query'
    | '/api/status'
  id:
    | '__root__'
    | '/'
    | '/dms'
    | '/inbox'
    | '/mentions'
    | '/api/action'
    | '/api/inbox'
    | '/api/query'
    | '/api/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DmsRoute: typeof DmsRoute
  InboxRoute: typeof InboxRoute
  MentionsRoute: typeof MentionsRoute
  ApiActionRoute: typeof ApiActionRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiStatusRoute: typeof ApiStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action': {
      id: '/api/action'
      path: '/api/action'
      fullPath: '/api/action'
      preLoaderRoute: typeof ApiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DmsRoute: DmsRoute,
  InboxRoute: InboxRoute,
  MentionsRoute: MentionsRoute,
  ApiActionRoute: ApiActionRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiStatusRoute: ApiStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
